// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.9.1'
        classpath 'com.google.gms:google-services:4.4.4'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

apply from: "variables.gradle"

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

subprojects {
    configurations.all {
        resolutionStrategy {
            force 'androidx.activity:activity:1.10.0'
            force 'androidx.activity:activity-ktx:1.10.0'
            force 'androidx.core:core:1.15.0'
            force 'androidx.core:core-ktx:1.15.0'
            force 'androidx.appcompat:appcompat:1.7.0'
            
            eachDependency { details ->
                if (details.requested.group == 'androidx.lifecycle') {
                    details.useVersion '2.8.7'
                }
                if (details.requested.group == 'androidx.activity') {
                    details.useVersion '1.10.0'
                }
            }
        }
    }
    afterEvaluate { project ->
        if (project.hasProperty('android')) {
            project.android {
                compileSdk = rootProject.ext.compileSdkVersion
                if (project.name == 'app') {
                    defaultConfig {
                        targetSdk = rootProject.ext.targetSdkVersion
                    }
                }
                compileOptions {
                    sourceCompatibility JavaVersion.VERSION_21
                    targetCompatibility JavaVersion.VERSION_21
                }
            }
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
